name: My first workflow
on: push
jobs: 
    first_job:
        runs-on: ubuntu-22.04
        steps:
        - name: Checkout
          uses: actions/checkout@main
      
        - name: multiline commands
          run: |
           echo "My first Github action job1"
           ls -lrta
           cat README.md
        
        - name: execute shell script
          run: ./ascii-script.sh