name: generate-ascii artwork
on: push
jobs: 
    ASCII_JOB:
        runs-on: ubuntu-22.04
        steps:
        - name: Checkout
          uses: actions/checkout@main
        
        - name: install cowsay program
          run: sudo apt-get install cowsay -y
        
        - name: Generate ASCII network
          run: cowsay -f dragon "run for cover, i am a dragon....RAWR" >> dragon.txt

        - name: test file exists
          run: grep -i "dragon" dragon.txt
        
        - name: read file
          run: cat dragon.txt

        - name: listing repo files
          run: ls -ltra