name: generate-ascii artwork
on: push
jobs: 
    ASCII_JOB:
        runs-on: ubuntu-22.04
        steps:
        - name: Checkout
          uses: actions/checkout@main
    install_job:
        needs: ASCII_JOB
        runs-on: ubuntu-22.04 
        steps:   
        - name: install cowsay program
          run: sudo apt-get install cowsay -y
    
        - name: sleep for 30 sec
          run: sleep 30

        - name: Generate ASCII network
          run: cowsay -f dragon "run for cover, i am a dragon....RAWR" >> dragon.txt

        - name: upload dragon file
          uses: actions/upload-artifact@v4
          with:
           name: dragon text file
           path: dragon.txt

    test_job:
        needs: install_job
        runs-on: ubuntu-22.04
        steps:
        - name: download dragon file
          uses: actions/download-artifact@v4
          with:
           name: dragon text file
           path: dragon.txt        
        - name: read file
          run: cat dragon.txt